### ISSUE TITLE
Not compatible with Livewire v2

### ISSUE THREAD

**Issue by ryangjchandler** [livewire/vue#17]
This plugin isn't compatible with Livewire v2. After updating, the following error is in the console:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/41837763/92506491-7595e880-f1fd-11ea-82d0-b9439a190d79.png">

Seems like the `beforeDomUpdate` hook has been removed and throws an error when an invalid hook is used.

**Comment by calebporzio** [comment]
Fixed, thanks Ryan!

**Comment by calebporzio** [comment]
(Fixed in version 0.3.x)

**Comment by ryatkins** [comment]
Hi @calebporzio - I tried out this fix, but still having issues.  Thanks @ryangjchandler for submitting the issue.

Livewire: 2.1.1
Vue: v2
Livewire-Vue: 0.3.0

Upgrading from Livewire 1.3 / 0.2.0

```
Uncaught TypeError: Cannot read property '__vue__' of null
    at index.js:24
    at MessageBus.js:17
    at Array.forEach (<anonymous>)
    at MessageBus.value (MessageBus.js:16)
    at Object.call (HookManager.js:36)
    at Object.callHook (Store.js:120)
    at Object.setInputValue (dom.js:150)
    at Object.setInputValueFromModel (dom.js:146)
    at node_initializer.js:22
    at Array.forEach (<anonymous>)
```

![image](https://user-images.githubusercontent.com/1211767/92549325-fd441d00-f226-11ea-990f-182d6c9a4621.png)

**Comment by thijsvdanker** [comment]
Looks like the `el` and `value` parameters are in the wrong order:

https://github.com/livewire/vue/blob/d4fac66312831e49333b1f810339c7e1f94b06a2/src/index.js#L22
```js
window.livewire.hook('interceptWireModelSetValue', (el, value) => {
    // If it's a vue component pass down the value prop.
    if (! el.__vue__) return
```

vs

https://github.com/livewire/livewire/blob/master/js/dom/dom.js#L150
```js
    setInputValue(el, value) {
        store.callHook('interceptWireModelSetValue', value, el)
```

**Comment by ryatkins** [comment]
FYI @calebporzio - this fix worked for me.  Many thanks @thijsvdanker

**Comment by calebporzio** [comment]
Thanks @thijsvdanker ! and thanks for verifying @ryatkins !
